### PR TITLE
Update golang-version default to 1.10.0

### PR DESCRIPTION
**Pull request by marians**
Let's use new go :)

### CODE REVIEW

**Comment by xh3b4sd** [comment]
I would like to get another approve.

**Comment by xh3b4sd** [comment]
+1 for more trust.

**Comment by marians** [comment]
Wow. That is _some_ undocumented repo... https://github.com/giantswarm/build-the-swarm

**Comment by JosephSalisbury** [comment]
It's also super old apparently! :D

**Comment by marians** [comment]
```
./build-the-swarm
2018/02/21 15:31:06 starting 14 builds over 8 workers
2018/02/21 15:31:08 failed to build: g8s-ingress-controller:
,
```

Not cool

**Comment by JosephSalisbury** [comment]
Yeah, looking at https://github.com/giantswarm/build-the-swarm/blob/master/projects.go, some of those repositories don't even exist. Ignore me :D

**Pull request merged**
