### PR TITLE
Use updated app library with apiextensions change to improve app CRs

### PR DESCRIPTION
**Pull request by rossf7**
Towards giantswarm/giantswarm#11556

### CODE REVIEW

**Comment by kopiczko** [comment]
@rossf7 should we merge this?

**Comment by rossf7** [comment]
It wasn't working correctly when I tested. The ugly empty fields were still there. I'll take another look this week.

**Comment by kopiczko** [comment]
How about this https://github.com/giantswarm/architect/pull/472 ? (I just added dependabot config)

**Comment by rossf7** [comment]
> How about this #472 ? (I just added dependabot config)

It won't break. So I'd say merge the dependabot PR and I'll close this?

I want to get back to this but I don't have time to work on it at the moment.

**Comment by kopiczko** [comment]
#472 merged.

**Pull request closed without merging**
