### PR TITLE
add custom --ldflags

### PR DESCRIPTION
**Pull request by jgsqware**
Add the possibility to add custom `ldflags` to the `go build` command.

It's especially useful to update on build time some variable *(eg. for version)*

```
architect build --help                                                                                                                                                                   21:44:22
build the project

Usage:
  architect build [flags]

Flags:
      --goarch string           value for $GOARCH (default "amd64")
      --golang-image string     golang image (default "quay.io/giantswarm/golang")
      --golang-version string   golang version (default "1.8.3")
      --goos string             value for $GOOS (default "linux")
  -h, --help                    help for build
      --ldflags string          value for custom -ldflags

Global Flags:
      --dry-run                    show what would be executed, but take no action
      --organisation string        organisation who owns the project (default "jgsqware")
      --project string             name of the project (default "a-beer-a-day")
      --registry string            docker registry (default "registry.giantswarm.io")
      --sha string                 git SHA1 to build (default "b58bbbc138e5593aa0cc9cdaf950c4e230dd0bbb")
      --working-directory string   working directory for architect (default "/Users/juliengarciagonzalez/workspace/go/src/github.com/jgsqware/a-beer-a-day")
```

### CODE REVIEW

**Comment by jgsqware** [comment]
Do you think it worth it?

**Comment by JosephSalisbury** [comment]
We largely use `architect` as part of our build flow, which we run with just `architect build` - see https://circleci.com/gh/giantswarm/api for example. I don't think this is a necessary change.

**Comment by xh3b4sd** [comment]
What about this? Can we merge? Can we close?

**Comment by jgsqware** [comment]
Was used during my interview ;) could be not relevant.

**Comment by xh3b4sd** [comment]
Does that mean that we can merge or close it?

**Comment by JosephSalisbury** [comment]
Closing for the cleanup god.

**Pull request closed without merging**
