### PR TITLE
Add configurable intercom app id, and set it for aws and leaseweb installations

### PR DESCRIPTION
**Pull request by oponder**
Related to: https://github.com/giantswarm/happa/issues/158

### CODE REVIEW

**Comment by oponder** [comment]
I'm actually not totally sure if this needs to be in architect.
It could just be set directly in Happa's kubernetes manifests.

WDYT @JosephSalisbury ?

**Comment by marians** [comment]
The only thing I can review here is the Intercom ID, and that looks okay.

**Comment by JosephSalisbury** [comment]
We have production and staging manifests for happa, we could set this there?

**Comment by JosephSalisbury** [comment]
I don't really see this changing between installations

**Comment by oponder** [comment]
Agreed, this doesn't belong in architect.

**Pull request closed without merging**
