### PR TITLE
Fail builds if DCO or LICENSE files are missing

### PR DESCRIPTION
**Pull request by JosephSalisbury**
Closes https://github.com/giantswarm/giantswarm/issues/5029

This will apply to *all* repos that `architect` builds, but I think having a switch based on public/private isn't necessary - if we should do it for public repos, we should do it for private repos too.

### CODE REVIEW

**Comment by JosephSalisbury** [comment]
I won't merge this till Monday at the earliest, and I'll make sure to give a good shout in #news-dev first.

**Comment by kopiczko** [comment]
What should we do with private repo? Put Apache2 license?

**Comment by JosephSalisbury** [comment]
Yeah!

**Comment by marians** [comment]
Why also check private repos?

**Comment by JosephSalisbury** [comment]
Mainly to keep it simpler / have one less rule to remember.

**Comment by JosephSalisbury** [comment]
https://media.giphy.com/media/g0mNCFSdDSjscSc5q9/giphy.gif

**Pull request merged**
