### PR TITLE
Add etcd-backup to all installations

### PR DESCRIPTION
**Pull request by r7vme**
Changes in installations repo to be done soon

### CODE REVIEW

**Comment by calvix** [comment]
Why would be the backup be only for  KVM provider? 
It make sense to  me to backup all enviroments

**Comment by r7vme** [comment]
Yeah, backups always should be done independently even if you have persistent storage.

**Comment by kopiczko** [comment]
I didn't notice it's merged LoL

**Comment by xh3b4sd** [comment]
All good. Only confusion about EBS on my side.

**Comment by r7vme** [comment]
@kopiczko it's not merged yet :) related chage was merged

**Comment by r7vme** [comment]
I'll merge as soon as CI will be green

**Comment by kopiczko** [comment]
> @kopiczko it's not merged yet :) related chage was merged

LoL Friday

@xh3b4sd approve?

**Pull request merged**
