### PR TITLE
Bumps default golang version to 1.8.0

### PR DESCRIPTION
**Pull request by JosephSalisbury**
Towards https://github.com/giantswarm/giantswarm/issues/1297

### CODE REVIEW

**Comment by xh3b4sd** [comment]
We should communicate here. How does the plan look like? I use `gvm` so I do not have issues with this. Are we sure all of our projects are able to build? The change this PR introduces is quite small but its implications are huge and right now I would like to prevent a lot of hustle to bump the go version.

**Comment by JosephSalisbury** [comment]
We've previously kept the discussion on people's local golang versions as "your responsibility, if it matches, then you'll have fewer issues". My plan was to announce the bump before/during/after merging.

With regards to build failures due to the version bump, I've just tested `api`, `aws-operator`, `kuberenetesd`, and `certctl` with golang 1.8, and no issues.

I think we're good here. golang compatability is pretty nice :D

**Comment by xh3b4sd** [comment]
I would say the plan should be to make every developer bump and work for a week and then merge architect.

**Comment by JosephSalisbury** [comment]
That sounds reasonable to me.

**Comment by JosephSalisbury** [comment]
see https://gigantic.slack.com/archives/C04TGHDEF/p1490187153628170 for announcement

let's hit this back next week

**Comment by JosephSalisbury** [comment]
```
17:45:18 ~/go/src/github.com/giantswarm/build-the-swarm (master)
$ ./build-the-swarm
2017/04/04 17:45:19 starting 14 builds over 8 workers
2017/04/04 17:45:21 built g8s-ingress-controller
2017/04/04 17:45:21 built g8s-etcd-operator
2017/04/04 17:45:28 built g8s-prometheus
2017/04/04 17:46:35 built certctl
2017/04/04 17:50:28 built companyd
2017/04/04 17:51:38 built cluster-service
2017/04/04 17:52:30 built testbot
2017/04/04 17:53:11 built api
2017/04/04 17:53:33 built tokend
2017/04/04 17:54:17 built userd
2017/04/04 17:57:13 built cert-operator
2017/04/04 17:57:26 built kvm-operator
2017/04/04 17:57:30 built kubernetesd
2017/04/04 17:57:31 built aws-operator
```

@rossf7 everything builds with 1.8, let's go let's go

**Pull request merged**
